name: Testing framework

on:
  repository_dispatch:
    types: [uk_pr_test]

jobs:
  pr-test:
    runs-on: ubuntu-latest
    steps:
      - name: Log incoming client_payload
        run: |
          echo "client_payload: ${{ toJson(github.event.client_payload) }}"

      - name: Checkout PR head repo and branch
        uses: actions/checkout@v4
        with:
          # repository is the full name e.g. owner/repo (sent as pr_repo_name)
          repository: ${{ github.event.client_payload.pr_repo_name }}
          # ref is the branch/ref name sent as pr_head_ref
          ref: ${{ github.event.client_payload.pr_head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print checked out commit and basic meta
        run: |
          echo "Checked-out repository: ${{ github.event.client_payload.pr_repo_name }}"
          echo "Checked-out ref: ${{ github.event.client_payload.pr_head_ref }}"
          echo "Current commit: $(git rev-parse HEAD)"
          echo "PR Number: ${{ github.event.client_payload.pr_number }}"
          echo "PR URL: ${{ github.event.client_payload.pr_url }}"

      - name: Run tests
        run: |
          echo "Start tests (replace with real commands)"
          # e.g.: make -C tests test
          # or: pytest -q
          echo "Done"
